trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    pushd tritronFrontend
    npm i handlebars
    npm i express
    npm install @types/jquery 
    npm install -g @angular/cli@7.3.8
    npm install
    npm audit fix
    npm remove --save typescript;
    npm i --save-dev typescript@2.6.2;
    npm i --save-dev rxjs@6.2.2
    npm i --save-dev rxjs-compat@6.2.2
    
    npm run build
    ng build --prod
  displayName: 'npm install and build'