version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
     
      - run:
          name: install-dependencies
          command: npm  i @angular/compiler-cli
      - run:
          name: build
          command: yarn start
          working_directory: ./WebApp
           